### ISSUE TITLE
Support for running on OSX

### ISSUE THREAD

**Issue by i-am-logger** [Sky360-Repository/simpletracker-ros2-ws#21]
from the development meeting today 11-13-22 , there is an issue with all nodes not able to access the configuration node. Might be the case of UDP issues on docker and OSX. 

@Micky-G FYI, do you know if lionel has a github account?

**Comment by Micky-G** [comment]
He does yes, @liolemaire

**Comment by i-am-logger** [comment]
great! @liolemaire can you put your logs here?

**Comment by liolemaire** [comment]
Hi, it worked for me on os x 12.5.1 (mpb intel 2020, ram 16gig), 
docker desktop : 4.14.1
I had to install Xquartz : 2.8.4
In xquartz, you need to issue the command 'xhost +' to allow connection to the x11 server from the container.
In vscode, I updated the devcontainer.json like this : 
'
"containerEnv": {
		// "DISPLAY": "${localEnv:DISPLAY}",
		"DISPLAY":"host.docker.internal:0",
'
