### ISSUE TITLE
 Find a way to capture and store tracks - RosBag

### ISSUE THREAD

**Issue by Micky-G** [Sky360-Repository/simpletracker-ros2-ws#26]
We need a way to store interesting tracks that are captured. There is currently no persistence logic or functionality in the application. RosBag appears to fit the purpose. https://docs.ros.org/en/foxy/Tutorials/Beginner-CLI-Tools/Recording-And-Playing-Back-Data/Recording-And-Playing-Back-Data.html

This option looks good as well but I don't think its free: https://community.rti.com/static/documentation/connext-dds/6.0.0/doc/manuals/recording_service/introduction.html

**Comment by liolemaire** [comment]
I was just playing with rosbag. it's a bit of trouble to install.
Shall I try to include it in the simpletracker container ?
